import { z } from "zod";

export const createBlogZodSchema = z.object({
    title: z.string({ required_error: "Title is required" })
        .min(3, "Title must be at least 3 characters")
        .max(200, "Title must be less than 200 characters"),
    content: z.string({ required_error: "Content is required" })
        .min(10, "Content must be at least 10 characters"),
    excerpt: z.string({ required_error: "Excerpt is required" })
        .max(300, "Excerpt cannot be longer than 300 characters"),
    coverImage: z.string().url("Cover image must be a valid URL").optional(),
    tags: z.array(z.string().min(1, "Tag cannot be empty")).optional(),
    slug: z.string().optional(), // auto-generated by pre-save hook
});

export const updateBlogZodSchema = z.object({
    title: z.string().min(3).max(200).optional(),
    content: z.string().min(10).optional(),
    excerpt: z.string().max(300).optional(),
    coverImage: z.string().url().optional(),
    tags: z.array(z.string().min(1)).optional(),
    slug: z.string().optional(),
});
